### ISSUE TITLE
/!facepalm and /!triplefacepalm do not work

### ISSUE THREAD

**Issue by xXAndrew28Xx** [Funnygatt/GasaiBot#2]
Hello Gatt. I have a horrible problem. The facepalm commands will not work so I can not express in the Skript discord chats how I feel about some situations. This is a serious issue and should be addressed immediately.

**Comment by Funnygatt** [comment]
Oh no. That is horrible. I'll fix later.

**Comment by xXAndrew28Xx** [comment]
#3 HAH I NINJAJED
